class CommandName
  BUY = 'buy'
  CITIES = 'cities'
  DEPOSIT = 'deposit'
  HELP = 'help'
  LOAD = 'load'
  NO = 'no'
  PRICES = 'prices'
  QUIT = 'quit'
  SAVE = 'save'
  SELL = 'sell'
  START = 'start'
  STASH = 'stash'
  STATUS = 'status'
  TRAVEL = 'travel'
  WAIT = 'wait'
  WITHDRAW = 'withdraw'
  YES = 'yes'
end
