products:
  - name: Lorem
    supply_range: 1..4
    standard_range: 5..10
    demand_range: 12..20
  - name: Ipsum
    supply_range: 5..9
    standard_range: 11..25
    demand_range: 30..55
  - name: Donec
    supply_range: 65..80
    standard_range: 100..150
    demand_range: 200..230
